blue_exp: 'default-a'
blue_ckpt: ''
blue_seed: 0
blue_algo: 'ou'
yellow_exp: 'default-b'
yellow_ckpt: ''
yellow_seed: 0
yellow_algo: 'ou'
index: 0

experiment: ''
device: 'cuda:0'
num_envs: 2048
seed: 42
num_eps: 5000
record: True
defaults:
  - vss: VSSPPO
  - vssdma: VSSDecentralizedMAPPO
  
# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .